"""empty message

Revision ID: 364905a7f3b6
Revises: c6ab9a59501b
Create Date: 2023-08-15 23:16:21.426124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '364905a7f3b6'
down_revision = 'c6ab9a59501b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('salt', sa.String(length=250), nullable=False))
        batch_op.drop_column('is_active')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('salt')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
